#!/usr/bin/env sh
set -eu

case "${1:-}" in
  enable)
    /usr/bin/systemctl start firewalld.service
    exec /usr/bin/systemctl enable firewalld.service
    ;;
  disable)
    /usr/bin/systemctl stop firewalld.service
    exec /usr/bin/systemctl disable firewalld.service
    ;;
  *)
    printf '%s\n' "usage: goblins-os-firewall enable|disable" >&2
    exit 64
    ;;
esac
